return {
    n = {
        ["<leader>bn"] = {":bn<CR>", desc = 'Buffer Next'},
        ["<leader>bp"] = {":bp<CR>", desc = 'Buffer previous'},
        -- ["<C-s>"] = ":w<CR>",
        -- ["<C-q>"] = ":q<CR>",
        -- ["<C-w>"] = ":wq<CR>",
        -- ["<C-f>"] = ":lua require('telescope.builtin').find_files()<CR>",
        -- ["<C-g>"] = ":lua require('telescope.builtin').live_grep()<CR>",
        -- ["<C-b>"] = ":lua require('telescope.builtin').buffers()<CR>",
        -- ["<C-p>"] = ":lua require('telescope.builtin').git_files()<CR>",
        -- ["<C-d>"] = ":lua require('telescope.builtin').lsp_workspace_diagnostics()<CR>",
        -- ["<C-l>"] = ":lua require('telescope.builtin').lsp_references()<CR>",
        -- ["<C-n>"] = ":lua require('telescope.builtin').lsp_document_symbols()<CR>",
        -- ["<C-m>"] = ":lua require('telescope.builtin').lsp_dynamic_workspace_symbols()<CR>",
        -- ["<C-/>"] = ":CommentToggle<CR>",
        -- ["<C-\\>"] = ":CommentToggle<CR>",
        -- ["<C-`>"] = ":CommentToggle<CR>",
        -- ["<C-~>"] = ":CommentToggle<CR>",
        -- ["<C-!>"] = ":CommentToggle<CR>",
        -- ["<C-@>"] = ":CommentToggle<CR>",
        -- ["<C-#>"] = ":CommentToggle<CR>",
        -- ["<C-$>"] = ":CommentToggle<CR>",
        -- ["<C-%>"] = ":CommentToggle<CR>",
        -- ["<C-^>"] = ":CommentToggle<CR>",
        -- ["<C-&>"] = ":CommentToggle<CR>",
        -- ["<C-*>"] = ":CommentToggle<CR>",
        -- ["<C-(>"] = ":CommentToggle<CR>",
        -- ["<C-)>"] = ":CommentToggle<CR>",
        -- ["<C-_>"] = ":CommentToggle<CR>",
        -- ["<C-+>"] = ":CommentToggle<CR>",
    },
}
